name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --verbose
          pip install flake8

      - name: Run flake8
        run: flake8 . --max-line-length 120 --exclude .git,__pycache__,env --ignore F522,F524,E252,W291,W293

  build-and-push:
    name: Build and push 
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/collection-tasks-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/collection-tasks-api:latest

  test-compose:
    name: Test Docker Compose
    runs-on: ubuntu-latest
    needs: build-and-push
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run docker-compose
        run: |
          docker-compose up --build -d
          sleep 5
          docker-compose down
